### ISSUE TITLE
[Bug] Can't connection OpenAi.

### ISSUE THREAD

**Issue by coolxitech** [zizmax/CraftGPT#13]
[20:06:40 WARN]: [CraftGPT] [Try 0] Non-OpenAI error: zip file closed
[20:06:40 WARN]: java.lang.IllegalStateException: zip file closed
[20:06:40 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
[20:06:40 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
[20:06:40 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
[20:06:40 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
[20:06:40 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[20:06:40 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[20:06:40 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[20:06:40 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[20:06:40 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[20:06:40 WARN]:        at CraftGPT-0.2.9.jar//io.reactivex.Single.subscribe(Single.java:2521)
[20:06:40 WARN]:        at CraftGPT-0.2.9.jar//io.reactivex.Single.blockingGet(Single.java:2001)
[20:06:40 WARN]:        at CraftGPT-0.2.9.jar//com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:319)
[20:06:40 WARN]:        at CraftGPT-0.2.9.jar//com.theokanning.openai.service.OpenAiService.createChatCompletion(OpenAiService.java:133)
[20:06:40 WARN]:        at CraftGPT-0.2.9.jar//acute.ai.CraftGPT.nonChatRequest(CraftGPT.java:473)
[20:06:40 WARN]:        at CraftGPT-0.2.9.jar//acute.ai.CraftGPT.tryNonChatRequest(CraftGPT.java:443)
[20:06:40 WARN]:        at CraftGPT-0.2.9.jar//acute.ai.CraftGPT$3.run(CraftGPT.java:290)
[20:06:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[20:06:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:06:40 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:06:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:06:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:06:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by zizmax** [comment]
When does this error happen? Has the connection ever worked for you before?

Also, please share your plugin list.
