### ISSUE TITLE
Could not pass event EntityMountEvent

### ISSUE THREAD

**Issue by gxlydlyf** [zizmax/CraftGPT#17]
```
[22:55:24] [Server thread/ERROR]: Could not pass event EntityMountEvent to CraftGPT v0.2.13
java.lang.NullPointerException: Cannot invoke "acute.ai.CraftGPT.getConfig()" because "acute.ai.EntityMountEventListener.craftGPT" is null
	at acute.ai.EntityMountEventListener.onPlayerMount(EntityMountEventListener.java:25) ~[CraftGPT-0.2.13.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1094.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.Entity.startRiding(Entity.java:2990) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.level.ServerPlayer.startRiding(ServerPlayer.java:2699) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.addPassenger(CraftEntity.java:460) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at ia.m.aB.aq(SourceFile:165) ~[ItemsAdder_3.6.4-release-2.jar:?]
	at ia.m.aB.ap(SourceFile:64) ~[ItemsAdder_3.6.4-release-2.jar:?]
	at ia.m.aB.a(SourceFile:79) ~[ItemsAdder_3.6.4-release-2.jar:?]
	at ia.m.ad.a(SourceFile:1462) ~[ItemsAdder_3.6.4-release-2.jar:?]
	at ia.m.aI.d(SourceFile:74) ~[ItemsAdder_3.6.4-release-2.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by zizmax** [comment]
Should be fixed as of 0.2.14. Please reopen if you see it again.
